name: Deploy Project
on: [push, workflow_dispatch]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  deploy-job:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy to production server
        run: |
          echo "Deploying to production server..."
          # Add your deployment commands here, e.g., scp, rsync, etc.